// ============================================================
// siteData.ts — AUTO-GENERATED by site_generator.py
// Do not edit manually. Re-run the generator to update.
// ============================================================

export type Variant = 'A' | 'B' | 'C' | 'D'

export interface ServiceItem {
  iconName: string
  name: string
  description: string
}

export interface ReviewItem {
  name: string
  rating: number
  text: string
  date: string
}

export interface WhyUsPoint {
  heading: string
  body: string
}

export interface ProcessStep {
  heading: string
  body: string
}

export interface FAQItem {
  question: string
  answer: string
}

export interface SiteData {
  businessName: string
  trade: string
  tagline: string
  phone: string
  email: string
  address: string
  city: string
  serviceArea: string
  googleBusinessUrl: string
  yearsExperience: number
  bookingUrl?: string
  variant: Variant
  hero: {
    heading: string
    subheading: string
    primaryCta: string
    secondaryCta: string
  }
  services: ServiceItem[]
  trustItems: string[]
  whyUs: {
    heading: string
    subheading: string
    points: WhyUsPoint[]
  }
  process: ProcessStep[]
  faqs: FAQItem[]
  reviews: ReviewItem[]
  seo: {
    title: string
    description: string
    canonicalUrl: string
  }
}

const siteData: SiteData = {
  businessName: 'PRO TOP roofing and building LTD',
  trade: 'Roofers',
  tagline: 'Birmingham\'s Trusted Roofing Specialists',
  phone: '+44 121 673 2752',
  email: 'info@protoproofingandbuildingltd.co.uk',
  address: 'Suite 2A, 6 Floor, Cobalt Square, 83-85 Hagley Rd, Birmingham B16 8QG, United Kingdom',
  city: 'Birmingham',
  serviceArea: 'Birmingham',
  googleBusinessUrl: 'https://maps.google.com',
  yearsExperience: 8,

  variant: 'A',

  hero: {
    heading: 'Professional Roofers Serving Birmingham Since 2013',
    subheading: 'PRO TOP Roofing and Building Ltd provides reliable roofing services across Birmingham with 11 years of experience. Our team delivers quality workmanship with a 4.9-star Google rating from 48+ satisfied customers.',
    primaryCta: 'Get a Free Quote',
    secondaryCta: 'Call Now',
  },

  services: [
    {
      iconName: 'Roof',
      name: 'Roof Repairs',
      description: 'We fix all types of roof damage including missing tiles, leaks, and storm damage. Our repairs come with a guarantee and use quality materials to ensure lasting results.',
    },
    {
      iconName: 'Home',
      name: 'New Roof Installation',
      description: 'Complete roof replacement service using high-quality materials and modern techniques. We handle everything from planning to completion with minimal disruption to your daily routine.',
    },
    {
      iconName: 'Droplets',
      name: 'Gutter Services',
      description: 'Professional gutter cleaning, repair, and replacement to protect your property from water damage. We ensure proper drainage and maintain your guttering system year-round.',
    },
    {
      iconName: 'Shield',
      name: 'Flat Roofing',
      description: 'Specialist flat roof installation and repair using EPDM, felt, and GRP materials. Our waterproof solutions are designed to withstand Birmingham\'s weather conditions.',
    },
    {
      iconName: 'Search',
      name: 'Roof Surveys',
      description: 'Comprehensive roof inspections to identify potential issues before they become costly problems. We provide detailed reports with photographs and recommended actions.',
    },
    {
      iconName: 'RefreshCw',
      name: 'Roof Maintenance',
      description: 'Regular maintenance programmes to extend your roof\'s lifespan and prevent unexpected repairs. We offer annual checks and emergency callout services throughout Birmingham.',
    },
  ],

  trustItems: [
    '11+ Years Experience',
    '4.9 Star Google Rating',
    'Free No-Obligation Quotes',
    'Local Birmingham Roofers'
  ],

  whyUs: {
    heading: 'Why Choose PRO TOP Roofing and Building Ltd?',
    subheading: 'With over a decade serving Birmingham, we combine local knowledge with professional expertise to deliver roofing solutions you can trust.',
    points: [
      {
        heading: 'Local Expertise',
        body: 'Based in Birmingham with 11 years of experience working on local properties. We understand the specific roofing challenges that Birmingham weather presents.',
      },
      {
        heading: 'Quality Guaranteed',
        body: 'All our work comes with comprehensive guarantees and we only use approved materials. Our 4.9-star Google rating reflects our commitment to excellent service.',
      },
      {
        heading: 'Fully Insured',
        body: 'Complete public liability insurance and professional certifications give you peace of mind. We handle all safety requirements and comply with building regulations.',
      },
      {
        heading: 'Fair Pricing',
        body: 'Transparent quotes with no hidden costs and competitive rates throughout Birmingham. We provide detailed breakdowns so you know exactly what you\'re paying for.',
      },
    ],
  },

  process: [
    {
      heading: 'Contact Our Team',
      body: 'Call us or request a quote online to discuss your roofing needs. We\'ll arrange a convenient time to visit your Birmingham property for a free assessment.',
    },
    {
      heading: 'Free Property Survey',
      body: 'Our experienced roofers will thoroughly inspect your roof and identify any issues. You\'ll receive a detailed report with photographs and our professional recommendations.',
    },
    {
      heading: 'Detailed Quote',
      body: 'We provide a comprehensive written quote with clear pricing and timeline. Our quotes are valid for 30 days with no hidden costs or surprise charges.',
    },
    {
      heading: 'Professional Installation',
      body: 'Our qualified team completes the work to the highest standards with minimal disruption. We clean up thoroughly and provide a guarantee on all completed roofing work.',
    },
  ],

  faqs: [
    {
      question: 'How quickly can you provide a quote?',
      answer: 'We typically provide quotes within 24-48 hours of your initial contact. Emergency roof repairs can often be assessed the same day across Birmingham.',
    },
    {
      question: 'Do you offer guarantees on your work?',
      answer: 'Yes, all our roofing work comes with comprehensive guarantees. The length varies depending on the type of work, from 12 months for repairs to 20 years for new installations.',
    },
    {
      question: 'Are you insured and certified?',
      answer: 'We carry full public liability insurance and hold all relevant trade certifications. Our team regularly updates training to maintain the highest professional standards.',
    },
    {
      question: 'What areas of Birmingham do you cover?',
      answer: 'We serve all areas of Birmingham and surrounding districts. Our central location means we can reach most properties within 30 minutes for emergency calls.',
    },
    {
      question: 'Do you work in all weather conditions?',
      answer: 'Safety is our priority, so we avoid working in dangerous conditions like high winds or storms. However, we offer emergency temporary repairs to prevent further damage until permanent work can be completed.',
    },
    {
      question: 'Can you help with insurance claims?',
      answer: 'Yes, we regularly work with insurance companies and can provide detailed reports and photographs. We\'ll help guide you through the claims process and liaise directly with assessors when needed.',
    },
  ],

  reviews: [
    {
      name: 'Sarah M',
      rating: 5,
      text: 'Excellent service from PRO TOP Roofing. They repaired storm damage to our roof quickly and professionally. The team was courteous and cleaned up perfectly afterwards.',
      date: 'November 2024',
    },
    {
      name: 'David L',
      rating: 5,
      text: 'Very impressed with the quality of work on our flat roof replacement. Fair pricing, arrived on time, and completed exactly as promised. Would definitely recommend to others in Birmingham.',
      date: 'October 2024',
    },
    {
      name: 'Janet R',
      rating: 5,
      text: 'Professional roof survey identified several issues we hadn\'t noticed. The repair work was completed efficiently and the guarantee gives us peace of mind. Great local Birmingham roofers.',
      date: 'September 2024',
    },
  ],

  seo: {
    title: 'PRO TOP Roofing and Building Ltd | Roofers in Birmingham',
    description: 'Professional roofers in Birmingham with 11 years experience. Roof repairs, installations & maintenance. 4.9★ rated, fully insured. Call +44 121 673 2752 for free quote.',
    canonicalUrl: 'https://preview-pro-top-roofing-and-building-ltd.vercel.app',
  },
}

export default siteData

// CSS custom properties injected by site_generator.py
// These override :root variables in index.css at runtime
export const siteTheme = {
  '--color-primary':  '#1B2D45',
  '--color-accent':   '#E85D26',
  '--color-bg':       '#FAFAF8',
  '--color-text':     '#1A1A1A',
  '--color-muted':    '#6B7280',
  '--color-border':   '#E5E5E5',
  '--font-heading':   "'Instrument Serif', Georgia, serif",
  '--font-body':      "'DM Sans', system-ui, sans-serif",
}
